# Generated by Django 4.1.1 on 2022-09-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('avatar_url', models.CharField(max_length=100)),
                ('github_url', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('bio', models.CharField(max_length=100)),
                ('join_date', models.CharField(max_length=100)),
                ('hireable', models.BooleanField()),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
