# Generated by Django 4.1.1 on 2022-09-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_candidate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hireable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
